### ISSUE TITLE
error thrown when attempting to edit a preexisting source-gall mapping

### ISSUE THREAD

**Issue by ddennism** [jeffdc/gallformers#398]
On the "Map Species & Sources" page:
1. Select all text in the mapped source field.
2. Try to type a different mapped source name.
3. Get a black screen with text "Application error: a client-side exception has occurred (see the browser console for more information)."

**Comment by ddennism** [comment]
console (Chrome):

framework-4ed89e9640adfb9e.js:1 
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at y (2891-f40c4db010f5d43f.js:1:32933)
    at j (2891-f40c4db010f5d43f.js:1:33202)
    at r.value (2891-f40c4db010f5d43f.js:1:59844)
    at ki (framework-4ed89e9640adfb9e.js:1:101200)
    at bi (framework-4ed89e9640adfb9e.js:1:100874)
    at yi (framework-4ed89e9640adfb9e.js:1:100410)
    at framework-4ed89e9640adfb9e.js:1:112247
    at ws (framework-4ed89e9640adfb9e.js:1:112762)
    at is (framework-4ed89e9640adfb9e.js:1:106481)
du @ framework-4ed89e9640adfb9e.js:1
a.componentDidCatch.t.callback @ framework-4ed89e9640adfb9e.js:1
Ua @ framework-4ed89e9640adfb9e.js:1
ki @ framework-4ed89e9640adfb9e.js:1
bi @ framework-4ed89e9640adfb9e.js:1
yi @ framework-4ed89e9640adfb9e.js:1
(anonymous) @ framework-4ed89e9640adfb9e.js:1
ws @ framework-4ed89e9640adfb9e.js:1
is @ framework-4ed89e9640adfb9e.js:1
jl @ framework-4ed89e9640adfb9e.js:1
cs @ framework-4ed89e9640adfb9e.js:1
Le @ framework-4ed89e9640adfb9e.js:1
Hr @ framework-4ed89e9640adfb9e.js:1
Kn @ framework-4ed89e9640adfb9e.js:1
Qn @ framework-4ed89e9640adfb9e.js:1


main-e059c18a936b56b9.js:1 
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at y (2891-f40c4db010f5d43f.js:1:32933)
    at j (2891-f40c4db010f5d43f.js:1:33202)
    at r.value (2891-f40c4db010f5d43f.js:1:59844)
    at ki (framework-4ed89e9640adfb9e.js:1:101200)
    at bi (framework-4ed89e9640adfb9e.js:1:100874)
    at yi (framework-4ed89e9640adfb9e.js:1:100410)
    at framework-4ed89e9640adfb9e.js:1:112247
    at ws (framework-4ed89e9640adfb9e.js:1:112762)
    at is (framework-4ed89e9640adfb9e.js:1:106481)
ee @ main-e059c18a936b56b9.js:1
fn @ main-e059c18a936b56b9.js:1
value @ main-e059c18a936b56b9.js:1
a.componentDidCatch.t.callback @ framework-4ed89e9640adfb9e.js:1
Ua @ framework-4ed89e9640adfb9e.js:1
ki @ framework-4ed89e9640adfb9e.js:1
bi @ framework-4ed89e9640adfb9e.js:1
yi @ framework-4ed89e9640adfb9e.js:1
(anonymous) @ framework-4ed89e9640adfb9e.js:1
ws @ framework-4ed89e9640adfb9e.js:1
is @ framework-4ed89e9640adfb9e.js:1
jl @ framework-4ed89e9640adfb9e.js:1
cs @ framework-4ed89e9640adfb9e.js:1
Le @ framework-4ed89e9640adfb9e.js:1
Hr @ framework-4ed89e9640adfb9e.js:1
Kn @ framework-4ed89e9640adfb9e.js:1
Qn @ framework-4ed89e9640adfb9e.js:1

main-e059c18a936b56b9.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ee @ main-e059c18a936b56b9.js:1
fn @ main-e059c18a936b56b9.js:1
value @ main-e059c18a936b56b9.js:1
a.componentDidCatch.t.callback @ framework-4ed89e9640adfb9e.js:1
Ua @ framework-4ed89e9640adfb9e.js:1
ki @ framework-4ed89e9640adfb9e.js:1
bi @ framework-4ed89e9640adfb9e.js:1
yi @ framework-4ed89e9640adfb9e.js:1
(anonymous) @ framework-4ed89e9640adfb9e.js:1
ws @ framework-4ed89e9640adfb9e.js:1
is @ framework-4ed89e9640adfb9e.js:1
jl @ framework-4ed89e9640adfb9e.js:1
cs @ framework-4ed89e9640adfb9e.js:1
Le @ framework-4ed89e9640adfb9e.js:1
Hr @ framework-4ed89e9640adfb9e.js:1
Kn @ framework-4ed89e9640adfb9e.js:1
Qn @ framework-4ed89e9640adfb9e.js:1
